server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: APPLICATION-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/applicationdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

springdoc:
  api-docs:
    path: /applications/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
